name: Run ESLint Linter

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.18.0'
        cache: 'npm'
    - name: Install npm
      run: npm install npm@11.16.0 -g
    - name: Install dependencies
      run: npm ci
    - name: Run lint 
      run: npm run lint --if-present